---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  mysql_host: "{{ .Values.application.mysql.host }}"
  mysql_port: "{{ .Values.application.mysql.port }}"
  mysql_db: "{{ .Values.application.mysql.db }}"
