---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}-mysql-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mysql_user: "{{ .Values.application.mysql.user | b64enc }}"
  mysql_password: "{{ .Values.application.mysql.password | b64enc }}"
